import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import { UserIcon } from "lucide-react";
import "./globals.css";
import { cn } from "@/lib/utils";
import { getSession } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { LanguageSwitcher, type LanguageCode } from "@/components/layout/language-switcher";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function isLanguageCode(value: string): value is LanguageCode {
  return value === "en" || value === "si" || value === "ta";
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // T-02-09: read the session only to decide what to render (guest CTA vs.
  // avatar) — never redirect() or throw here, so guest browsing on every
  // other page stays completely unaffected by this file.
  const session = await getSession();
  let user: { name: string | null; phone: string; languagePref: string } | null = null;
  if (session.userId) {
    user = await prisma.user.findUnique({
      where: { id: session.userId },
      select: { name: true, phone: true, languagePref: true },
    });
  }

  const cookieLangPref = (await cookies()).get("lang_pref")?.value ?? "en";
  const rawLangPref = user?.languagePref ?? cookieLangPref;
  const initialLangValue: LanguageCode = isLanguageCode(rawLangPref) ? rawLangPref : "en";

  const initials = user?.name ? user.name.trim().charAt(0).toUpperCase() : null;

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between gap-4 border-b border-border px-4 py-3 sm:px-6">
          <Link href="/" className="text-lg font-semibold tracking-tight">
            LankaReview
          </Link>
          <div className="flex items-center gap-3">
            <LanguageSwitcher isLoggedIn={Boolean(user)} initialValue={initialLangValue} />
            {user ? (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <button
                    type="button"
                    className="flex items-center gap-2 rounded-md px-1.5 py-1 text-sm font-medium hover:bg-muted"
                  >
                    <Avatar size="sm">
                      <AvatarFallback>
                        {initials ?? <UserIcon className="size-4" />}
                      </AvatarFallback>
                    </Avatar>
                    <span className="hidden sm:inline">{user.name ?? "Account"}</span>
                  </button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <form action="/api/auth/logout" method="post" className="contents">
                    <DropdownMenuItem asChild>
                      <button type="submit" className="w-full text-left">
                        Log out
                      </button>
                    </DropdownMenuItem>
                  </form>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <Button asChild size="sm" className="bg-brand-accent text-white hover:bg-brand-accent/90">
                <Link href="/login">Log in</Link>
              </Button>
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
